# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f033db957b453ab8aad3e347b6d8769a6310b0ea0782bdb08ad577a16eb4aa92a870588c6e1beece9a07dacb214623ab11198f4fb1b4d614d8fb25637e88398c

test:
  secret_key_base: bc5462b5bb7e07bc9e6e4e7e64d33c8b5332714b8ab7e39f76c2adc310093be5f08655ce61ab35ff5bb14acc99468296ad0e03498e8cc717bc21aa22ff76312f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
